image:
    - MacOS
    - Visual Studio 2015
    - Visual Studio 2017
    - Ubuntu 

build: off

init:
  - git config --global core.autocrlf input

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'

for:
-
  matrix:
    only:
      - image: Ubuntu

  artifacts:
    - path: ./files/jvm/target/classes/native/x86_64/libswoval-files0.so
      name: libswoval-files0.so

  install:
    - curl -sL https://github.com/sbt/sbt/releases/download/v1.4.4/sbt-1.4.4.tgz > ~/sbt-bin.tgz
    - mkdir ~/sbt
    - tar -xf ~/sbt-bin.tgz --directory ~/sbt
    - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh
    - jabba install adopt@1.8.0-222
    - jabba use adopt@1.8.0-222
    - export PATH="~/sbt/sbt/bin:$PATH"
    - export JAVA_HOME="~/.jabba/jdk/adopt@1.8.0-222"
    - export PATH="$PATH:$JAVA_HOME/bin"

  test_script:
    - sbt "filesJVM/jacoco" "travisQuickListReflectionTest" "allTests"

-
  matrix:
    only:
      - image: MacOS

  artifacts:
    - path: ./files/jvm/target/classes/native/x86_64/libswoval-files0.dylib
      name: libswoval-files0.dylib

  install:
    - curl -sL https://github.com/sbt/sbt/releases/download/v1.4.4/sbt-1.4.4.tgz > ~/sbt-bin.tgz
    - mkdir ~/sbt
    - tar -xf ~/sbt-bin.tgz --directory ~/sbt
    - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh
    - jabba install adopt@1.8.0-222
    - jabba use adopt@1.8.0-222
    - export PATH="~/sbt/sbt/bin:$PATH"
    - export JAVA_HOME="~/.jabba/jdk/adopt@1.8.0-222"
    - export PATH="$PATH:$JAVA_HOME/bin"

  test_script:
    - sbt "filesJVM/jacoco" "travisQuickListReflectionTest" "allTests"

-
  matrix:
    only:
      - image: Visual Studio 2015
      - image: Visual Studio 2017

  artifacts:
  - path: ./files/jvm/target/classes/native/x86_64/swoval-files0.dll
    name: swoval-files0.dll

  install:
    - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
    - SET PATH=%JAVA_HOME%\bin;%PATH%

    - ps: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        if (!(Test-Path -Path "C:\sbt" )) {
          (new-object System.Net.WebClient).DownloadFile(
            'https://github.com/sbt/sbt/releases/download/v1.4.4/sbt-1.4.4.zip',
            'C:\sbt-bin.zip'
          )
          [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
        }
    - SET PATH=C:\sbt\sbt\bin;%PATH%
    - SET SBT_OPTS=-Xmx2g -Dswoval.format=false -Dfile.encoding=UTF8 -Dswoval.skip.native=true -Dswoval.fork.tests=true -Dswoval.alltests.iterations=50

  test_script:
    - sbt "filesJVM/jacoco" "travisQuickListReflectionTest" "allTests"
