// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import SwovalProviderImpl._

object SwovalProviderImpl {

  private val impl: SwovalProvider = load()

  def getDefaultProvider(): SwovalProvider = impl

  private def load(): SwovalProvider = {
    val userDefined: SwovalProvider = SwovalProviderFactory.loadProvider()
    if (userDefined != null) userDefined else new Impl()
  }

  private class Impl extends SwovalProvider {

    val fileTreeRepositoryProvider: FileTreeRepositoryProvider =
      new FileTreeRepositoryProviderImpl()

    val pathWatcherProvider: PathWatcherProvider =
      new PathWatcherProviderImpl()

    override def getFileTreeRepositoryProvider(): FileTreeRepositoryProvider =
      fileTreeRepositoryProvider

    override def getPathWatcherProvider(): PathWatcherProvider =
      pathWatcherProvider

  }

}

class SwovalProviderImpl extends SwovalProvider {

  override def getFileTreeRepositoryProvider(): FileTreeRepositoryProvider =
    SwovalProviderImpl.impl.getFileTreeRepositoryProvider

  override def getPathWatcherProvider(): PathWatcherProvider =
    SwovalProviderImpl.impl.getPathWatcherProvider

}
