// Do not edit this file manually. It is autogenerated.

package com.swoval.files

trait SwovalProvider {

  def getFileTreeRepositoryProvider(): FileTreeRepositoryProvider

  def getPathWatcherProvider(): PathWatcherProvider

}
